version: '3'

services:
  app:
    build:
      context: .
      args:
        VARIANT: '2.7-bullseye'
        BUNDLER_VERSION: '2.2.17'
        RAILS_VERSIONS: '6.0.4'
        NODE_VERSION: '16'
    environment:
      BINDING: 0.0.0.0
    volumes:
      - ..:/home/vscode/environment:cached
      - bundle-volume:/usr/local/bundle
    command: sleep infinity
volumes:
  bundle-volume:
